### ISSUE TITLE
Update contact email in the code of conduct

### ISSUE THREAD

**Issue by cameronsamuels** [cameronsamuels/memerator#103]

**Comment by mackmmiller** [comment]
What should the contact email be updated to?

**Comment by cameronsamuels** [comment]
If you choose to buy a domain, you should update it to a `@domain` email. If not, you can make it an `@gmail.com` email or whatever other platform you want.

**Comment by cameronsamuels** [comment]
Sorry, I meant to say, if @Pipe-to-Grep buy's a domain. Sorry for the confusion, @mackmmiller.
