### ISSUE TITLE
Camera on Desktop

### ISSUE THREAD

**Issue by Pipe-to-Grep** [cameronsamuels/memerator#39]
Allow a PC user to take a picture with their webcam.

**Comment by CameronSamuels** [comment]
Great idea. We can look into this more.

**Comment by Pipe-to-Grep** [comment]
I think I found a very simple way. Trying with a pull request now.

**Comment by Pipe-to-Grep** [comment]
https://gist.github.com/Pipe-to-Grep/9955fdf699c42458c51c8d2281aa2114

I recommend implementing into another button. I'm not sure how to do it, but this gist should give you all the code you need.

**Comment by CameronSamuels** [comment]
Maybe it would be a button like you said, but only show when a computer is present (don’t show on mobile).

**Comment by Pipe-to-Grep** [comment]
Yeah, just about to say add detection for mobile and desktop

**Comment by CameronSamuels** [comment]
Ok, so make a branch and submit a PR for this.
